app = "backbrain5"
primary_region = "fra"

[build]
  # Dockerfile autodetected

[env]
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[http_service.checks]]
    interval = "15s"
    timeout = "3s"
    method = "GET"
    path = "/health"

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/ready"
