app = "backbrain5-staging"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  ENABLE_PUBLIC_ALIAS = "false"
  PUBLIC_WRITE_ENABLED = "false"
  RATE_LIMIT_KEY_STRATEGY = "apikey"
  SUMMARY_MODEL = "gpt-4o-mini"
  SUMMARIZER_PROVIDER = "heuristic"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  method = "get"
  path = "/health"
