"""add new models (FileORM/SummaryORM/JobType sync)

Revision ID: 7f6a4ec6f819
Revises: 1c39e24ffdce
Create Date: 2025-08-18 06:06:34.158469

"""
from typing import Sequence, Union

# (No operations; imports removed)


# revision identifiers, used by Alembic.
revision: str = '7f6a4ec6f819'
down_revision: Union[str, None] = '1c39e24ffdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Neutralized migration (was destructive autogen). Intentionally left as no-op.
    # Original autogenerated operations dropped tables & columns; replaced to protect existing data.
    pass


def downgrade() -> None:
    # Neutralized reverse operation (no-op).
    pass
