"""add new models (FileORM/SummaryORM/JobType sync)

Revision ID: 7f6a4ec6f819
Revises: 1c39e24ffdce
Create Date: 2025-08-18 06:06:34.158469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6a4ec6f819'
down_revision: Union[str, None] = '1c39e24ffdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_file_id', table_name='embeddings')
    op.drop_index('ix_embeddings_model', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_table('file_tags')
    op.drop_table('tags')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_summarizer_usage_created_at', table_name='summarizer_usage')
    op.drop_table('summarizer_usage')
    op.alter_column('files', 'size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_files_sha256', table_name='files')
    op.create_index(op.f('ix_files_original_name'), 'files', ['original_name'], unique=False)
    op.drop_column('files', 'created_at')
    op.alter_column('jobs', 'input_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_jobs_file_id'), 'jobs', ['file_id'], unique=False)
    op.drop_constraint('fk_jobs_file_id_files', 'jobs', type_='foreignkey')
    op.alter_column('summaries', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.drop_column('summaries', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('model', sa.VARCHAR(), nullable=False))
    op.create_foreign_key(None, 'summaries', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.alter_column('summaries', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('fk_jobs_file_id_files', 'jobs', 'files', ['file_id'], ['id'])
    op.drop_index(op.f('ix_jobs_file_id'), table_name='jobs')
    op.alter_column('jobs', 'input_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('files', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_index(op.f('ix_files_original_name'), table_name='files')
    op.create_index('ix_files_sha256', 'files', ['sha256'], unique=False)
    op.alter_column('files', 'size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_table('summarizer_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('model', sa.VARCHAR(), nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('file_name', sa.VARCHAR(), nullable=True),
    sa.Column('prefix', sa.VARCHAR(), nullable=True),
    sa.Column('fallback', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summarizer_usage_created_at', 'summarizer_usage', ['created_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('key_hash', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('revoked_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=1)
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('file_tags',
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('vector', sa.VARCHAR(), nullable=False),
    sa.Column('model', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embeddings_model', 'embeddings', ['model'], unique=False)
    op.create_index('ix_embeddings_file_id', 'embeddings', ['file_id'], unique=False)
    # ### end Alembic commands ###
